import type { Metadata } from "next"
import { Poppins } from "next/font/google"

import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "next-themes"

import "./globals.css"

const font = Poppins({
  display: "block",
  variable: "--font-poppins",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  style: "normal",
})

export const metadata: Metadata = {
  title: "Tiny Todo App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className} select-none antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          {children}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  )
}
